# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'faceIDLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for faceIDLogin

pod 'Firebase/Auth'

  target 'faceIDLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'faceIDLoginUITests' do
    # Pods for testing
  end

end
